name: Simple Test

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Say Hello
        run: echo "Hello, World!"